CREATE TABLE `tokens` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `symbol` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `logo_url` varchar(512) DEFAULT NULL,
  `website_url` varchar(512) DEFAULT NULL,
  `twitter_url` varchar(512) DEFAULT NULL,
  `telegram_url` varchar(512) DEFAULT NULL,
  `token_address` varchar(50) NOT NULL,
  `decimals` int NOT NULL,
  `is_risk_token` tinyint(1) DEFAULT '0',
  `total_supply` decimal(30,8) NOT NULL,
  `first_seen_timestamp` bigint DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `meta_uri` text,
  `token_create_ts` bigint DEFAULT NULL,
  `sol_scan_image` varchar(255) DEFAULT NULL,
  `latest_price` decimal(20,12) DEFAULT '0.000000000000',
  `latest_price_update_ts` bigint DEFAULT NULL,
  `creator_address` varchar(255) DEFAULT NULL,
  `create_tx` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token_address` (`token_address`),
  KEY `idx_name` (`name`),
  KEY `idx_symbol` (`symbol`),
  KEY `idx_is_risk_token` (`is_risk_token`)
) ENGINE=InnoDB AUTO_INCREMENT=233091 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci